#!/usr/bin/env python
from __future__ import print_function

import condor_restd

print(condor_restd.__doc__)
for epname in condor_restd.PUBLIC_ENDPOINTS:
    print("*** %s ***\n%s\n" % (epname, getattr(condor_restd, epname).__doc__))
