#!/usr/bin/env python
from __future__ import print_function

import apid

print(apid.__doc__)
for epname in apid.PUBLIC_ENDPOINTS:
    print("*** %s ***\n%s\n" % (epname, getattr(apid, epname).__doc__))
